Plasmoid drift
chalmersplasmatheory/DREAM pull request #249
Opened 2023-09-04 08:13 UTC by liamanton

2023-09-26 18:20 UTC, vaoskar requested changes
Really nice work! As far as I can tell this should work (except for some small mistakes that are mostly my fault...) for the test cases we have used! There are just a few simplifications of the implementation that would be good to alleviate to make the code work for a more general case before merging.

2023-09-26 18:20 UTC, vaoskar commented on src/Equations/SPIHandler.cpp
>              if(rCoordPNext[ip]>rCoordPPrevious[ip]){
I know this is mostly on me, but the loop condition here should be ir<nr-nbrShiftGridCell[ip] (before we have only used shifts of one grid cell and didn't plan well enough for the future...). Also, one should set depositionProfilesAllShards[ir*nShard+ip] = 0 for ir>nbrShiftGridCell[ip] (and make the corresponding changes for the rCoordPNext[ip]<rCoordPPrevious[ip]-case).

2023-11-07 19:34 UTC, vaoskar submitted a review, later dismissed
Great job! I only found some small things to change, and it felt easier to just fix them than writing detailed enough instructions for how to do it, so I fixed them myself. FYI I summarise the changes below:

There were a couple of places where you replaced Zavg0 where it shouldn't be replaced. 

I managed to make sure the drift is only calculated in the first iteration, so that we can simply get the conductivity directly from RunawayFluid in the first iteration and then just save it, which helps to make sure we use the same conductivity mode in both classes. 

I saw some errors in the logic on how to shift the deposition profiles, and some changes had to be done to ensure compatibility with the prescribed drift and the shift of the heat absorbed into the cloud.

Finally, you seemed to have made some potentially unintentional changes in the example running script, so I reverted it to use the same parameters as in the original case. I don't know what parameters you used in the example in the overleaf documentation, but perhaps you want to update that.

With these changes in place, it seems to work fine, as far as I can tell at least, so for me it is good to go! Does @hoppe93 want to take a look before we merge?

2024-01-11 14:01 UTC, hoppe93 requested changes
Impressive work! :D I have a number of questions/comments though which will need to be addressed before we merge.

2024-01-11 14:01 UTC, hoppe93 commented on src/Equations/SPIHandler.cpp
> +    int temp = 0;
``int_t``?

2024-04-04 15:31 UTC, hoppe93 commented on src/Equations/SPIHandler.cpp
> +    sigma = rf->GetElectricConductivity(irp[ip]);// As this function will only be called during the first newton iteration of each time step, sigma will be the conductivity from the previous time ste
If ``RunawayFluid`` is rebuilt before ``SPIHandler`` you should get the conductivity for the current time step, and not for the "previous time step" as indicated in the comment. If you just want "some conductivity", this is fine, but the comment is inaccurate in that case.

(The ``RunawayFluid`` object is always rebuilt with the best available solution for the current time ``t``, so I would say it is "rebuilt based on values from the latest time step even if discarded". I don't see how that would be strange? To me that sounds like the expected behaviour of a Newton solver?)

2024-07-03 18:16 UTC, hoppe93 requested changes
Some things still need addressing, in particular regarding memory handling and leaks.

2024-07-03 18:16 UTC, hoppe93 commented on src/Settings/SPIHandler.cpp
> +            isotopesDrift[i] = (len_t)_isotopesDrift[i];
(I will take care of this)

2024-07-03 18:16 UTC, hoppe93 commented on src/Settings/SPIHandler.cpp
> +        nbrShiftGridCell[i] = (int_t)_nbrShiftGridCell[i];
(I will take care of this)

2024-07-03 19:00 UTC, hoppe93 requested changes
Found another issue which must be resolved.

2024-07-03 19:00 UTC, hoppe93 commented on src/Equations/SPIHandler.cpp
> +                    printf("SPIHandler: Using other molarFractions other than deuterium and neon will lead to urealistic ablating.");
This needs to be turned into a warning (i.e. using the ``DREAM::IO::PrintWarning()`` function, with an appropriate warning ID).

2024-07-03 19:13 UTC, hoppe93 requested changes
Found some additional things which need addressing.

2024-07-03 19:13 UTC, hoppe93 commented on src/Equations/SPIHandler.cpp
> +    this->TDrift=TDrift;
``this->TDrift`` is allocated in ``AllocateQuantities()``, but then immediately overwritten here, leading to a memory leak. Is this really the intended behaviour? Should ``TDrift`` really be allocated in ``AllocateQuantities()``? (if not, the ``delete [] TDrift`` should probably be moved directly to the destructor?

2024-07-03 19:13 UTC, hoppe93 commented on src/Equations/SPIHandler.cpp
>  		            pelletDeuteriumFraction[ip]+=molarFraction[offset+ip];
Why is this ``+=`` and not just ``=``? At this point, ``pelletDeuteriumFraction`` is uninitialized and could contain garbage values. It must therefore either be properly initialized first, or we should turn ``+=`` into ``=``.

2024-07-03 19:13 UTC, hoppe93 commented on src/Equations/SPIHandler.cpp
> +            if(nbrShiftGridCell[ip]<0){
Somehow, the code is getting to this point without ``nbrShiftGridCell`` being initialized (it is allocated, but its elements have not been set to any particular values).

2024-07-04 11:23 UTC, hoppe93 approved these changes
This looks ready to merge now!

2024-07-04 11:40 UTC, merged