Approximate kinetic ionization mode
chalmersplasmatheory/DREAM pull request #298
Opened 2024-05-28 13:25 UTC by peterhalldestam

Added ionization mode in which the runaway electron distribution is assumed to be mono-energetic delta-function. For more details, see doc/notes/kinioniz_approx.tex and examples/kinioniz_approx/compare.py for example usage.

The ionization mode is implemented as an additional mode to make it backwards compatible and can now be used both in fluid and kinetic simulations.

2024-05-31 15:16 UTC, hoppe93 requested changes
Very nice work! :D I only have some small comments in a few places, in particular on comments and the naming of the new mode.

Also, I noted that the vast majority of modifications were just additions of single spaces here and there. I suspect it's coming from some setting in your editor? While they don't cause any issues in the code at all, they make it a bit more difficult to navigate through the diffs on GitHub, so it would be nice if they could be avoided in future pull requests :)

2024-05-31 15:16 UTC, hoppe93 commented on include/DREAM/OtherQuantityHandler.hpp
> +            std::vector<IonFluidRunawayIonizationTerm*> f_re_kin_approx_rates;
Isn't it confusing if this variable has ``f_re`` in the name, even though it has nothing to do with ``f_re``? I would propose a name such as ``n_re_kin_rates`` instead.

2024-05-31 15:16 UTC, hoppe93 commented on py/DREAM/Settings/Equations/IonSpecies.py
> +IONIZATION_MODE_APPROX_RE=4
I propose we name this ``IONIZATION_MODE_FLUID_RE`` instead.

2024-05-31 15:16 UTC, hoppe93 commented on src/Settings/Equations/ions.cpp
> +    bool includeKineticIonizationApprox = (ionization_mode == OptionConstants::EQTERM_IONIZATION_MODE_APPROX_RE);
I propose this variable is renamed ``includeFluidREIonization``.

2024-05-31 15:16 UTC, hoppe93 commented on src/Equations/Fluid/IonFluidRunawayIonizationTerm.cpp
> +    // possible to use an instance of IonKineticIonizationTerm, without having a MomentumGrid, to use the method for calculating sigma?
What does this comment mean?

2024-05-31 15:17 UTC, hoppe93 commented
Also, could you merge in the latest master to this branch?

2024-06-15 13:35 UTC, peterhalldestam commented on py/DREAM/Settings/OtherQuantities.py
> +        'fluid/kinioniz_approx_vsigma',
Good idea. I have changed it to `kinioniz_vsigma`, but this had the side effect of being identified together with `hottail/kinioniz_vsigma` and `runaway/kinioniz_vsigma` in `OtherQuantities.SPECIAL_TREATMENT` and tries to load it as another `OtherIonSpeciesKineticQuantity`. This raised an exception.

I figured the easiest solution was to add an if-statement in `OtherQuantities.setQuantity()` that checks if it's categorised as "fluid". I'm not sure if this is the best way to do it, so let me know if you have any suggestions! :)

2024-08-22 13:26 UTC, hoppe93 requested changes
Very nice! Now the examples works (very well) for me. I just have one question on the ``OtherQuantities.py`` file, which should hopefully be very quick to sort out.

I also made a small (and unrelated to your changes) change of the ``tools/ADAS/rates.py`` file. It can simplify the use of those routines in various places, but does not impact any other areas of DREAM at the moment.

2024-08-28 14:47 UTC, peterhalldestam commented on py/DREAM/Output/OtherQuantities.py
> +            elif self.name == 'fluid':
It was in an effort to be able to keep the same name for the RE ionisation rate also used in the kinetic setups, but it was poorly implemented. An easier solution is to use a different name entirely, which I have done now!

2024-08-28 15:02 UTC, hoppe93 submitted a review, later dismissed
Looks good! :)

2024-08-29 10:44 UTC, hoppe93 approved these changes
Looks very good!

2024-08-29 10:45 UTC, merged